from django.apps import AppConfig


class ProductsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'products'

    def ready(self):
        from vectordb.shortcuts import autosync_model_to_vectordb
        from .models import (
            AirConditioners, AllAppliances, AllBooks, AllCarAndMotorbikeProducts, AllElectronics, AllEnglish,
            AllExerciseAndFitness, AllGroceryAndGourmetFoods, AllHindi, AllHomeAndKitchen, AllMoviesAndTvShows,
            AllMusic, AllPetSupplies, AllSportsFitnessAndOutdoors, AllVideoGames, AmazonFashion, AmazonPharmacy,
            AmazonProducts, BabyBathSkinAndGrooming, BabyFashion, BabyProducts, Backpacks, Badminton, BagsAndLuggage,
            Ballerinas, BeautyAndGrooming, BedroomLinen, BluRay, CameraAccessories, Cameras, CampingAndHiking,
            CarAccessories, CarElectronics, CarParts, CarAndBikeCare, CardioEquipment, CasualShoes, ChildrensBooks,
            Clothing, CoffeeTeaAndBeverages, Cricket, Cycling, Diapers, DietAndNutrition, DogSupplies,
            EntertainmentCollectibles, EthnicWear, ExamCentral, FashionSalesAndDeals, FashionSandals,
            FashionAndSilverJewellery, FictionBooks, FilmSongs, FineArt, FitnessAccessories, Football, FormalShoes,
            Furniture, GamingAccessories, GamingConsoles, GardenAndOutdoors, GoldAndDiamondJewellery,
            HandbagsAndClutches, Headphones, HealthAndPersonalCare, HeatingAndCoolingAppliances, HomeAudioAndTheater,
            HomeDcor, HomeEntertainmentSystems, HomeFurnishing, HomeImprovement, HomeStorage, HouseholdSupplies,
            IndianClassical, IndianLanguageBooks, IndoorLighting, IndustrialAndScientificSupplies, Innerwear,
            InternationalMusic, InternationalToyStore, JanitorialAndSanitationSupplies, Jeans, Jewellery, KidsClothing,
            KidsFashion, KidsShoes, KidsWatches, KindleEbooks, KitchenStorageAndContainers, KitchenAndDining,
            KitchenAndHomeAppliances, LabAndScientific, LingerieAndNightwear, LuxuryBeauty, MakeUp, MensFashion,
            MotorbikeAccessoriesAndParts, MusicalInstrumentsAndProfessionalAudio, NursingAndFeeding, PcGames, Pantry,
            PersonalCareAppliances, Refrigerators, RefurbishedAndOpenBox, Rucksacks, Running, StemToysStore, SchoolBags,
            SchoolTextbooks, SecurityCameras, SewingAndCraftSupplies, Shirts, Shoes, SnackFoods, Speakers,
            SportsCollectibles, SportsShoes, Sportswear, StrengthTraining, StrollersAndPrams, SubscribeAndSave,
            SuitcasesAndTrolleyBags, Sunglasses, TShirtsAndPolos, Televisions, TestMeasureAndInspect, Textbooks,
            TheDesignerBoutique, ToysGiftingStore, ToysAndGames, TravelAccessories, TravelDuffles, ValueBazaar,
            VideoGamesDeals, Wallets, WashingMachines, Watches, WesternWear, WomensFashion, Yoga
        )

        autosync_model_to_vectordb(AirConditioners)
        autosync_model_to_vectordb(AllAppliances)
        autosync_model_to_vectordb(AllBooks)
        autosync_model_to_vectordb(AllCarAndMotorbikeProducts)
        autosync_model_to_vectordb(AllElectronics)
        autosync_model_to_vectordb(AllEnglish)
        autosync_model_to_vectordb(AllExerciseAndFitness)
        autosync_model_to_vectordb(AllGroceryAndGourmetFoods)
        autosync_model_to_vectordb(AllHindi)
        autosync_model_to_vectordb(AllHomeAndKitchen)
        autosync_model_to_vectordb(AllMoviesAndTvShows)
        autosync_model_to_vectordb(AllMusic)
        autosync_model_to_vectordb(AllPetSupplies)
        autosync_model_to_vectordb(AllSportsFitnessAndOutdoors)
        autosync_model_to_vectordb(AllVideoGames)
        autosync_model_to_vectordb(AmazonFashion)
        autosync_model_to_vectordb(AmazonPharmacy)
        autosync_model_to_vectordb(AmazonProducts)
        autosync_model_to_vectordb(BabyBathSkinAndGrooming)
        autosync_model_to_vectordb(BabyFashion)
        autosync_model_to_vectordb(BabyProducts)
        autosync_model_to_vectordb(Backpacks)
        autosync_model_to_vectordb(Badminton)
        autosync_model_to_vectordb(BagsAndLuggage)
        autosync_model_to_vectordb(Ballerinas)
        autosync_model_to_vectordb(BeautyAndGrooming)
        autosync_model_to_vectordb(BedroomLinen)
        autosync_model_to_vectordb(BluRay)
        autosync_model_to_vectordb(CameraAccessories)
        autosync_model_to_vectordb(Cameras)
        autosync_model_to_vectordb(CampingAndHiking)
        autosync_model_to_vectordb(CarAccessories)
        autosync_model_to_vectordb(CarElectronics)
        autosync_model_to_vectordb(CarParts)
        autosync_model_to_vectordb(CarAndBikeCare)
        autosync_model_to_vectordb(CardioEquipment)
        autosync_model_to_vectordb(CasualShoes)
        autosync_model_to_vectordb(ChildrensBooks)
        autosync_model_to_vectordb(Clothing)
        autosync_model_to_vectordb(CoffeeTeaAndBeverages)
        autosync_model_to_vectordb(Cricket)
        autosync_model_to_vectordb(Cycling)
        autosync_model_to_vectordb(Diapers)
        autosync_model_to_vectordb(DietAndNutrition)
        autosync_model_to_vectordb(DogSupplies)
        autosync_model_to_vectordb(EntertainmentCollectibles)
        autosync_model_to_vectordb(EthnicWear)
        autosync_model_to_vectordb(ExamCentral)
        autosync_model_to_vectordb(FashionSalesAndDeals)
        autosync_model_to_vectordb(FashionSandals)
        autosync_model_to_vectordb(FashionAndSilverJewellery)
        autosync_model_to_vectordb(FictionBooks)
        autosync_model_to_vectordb(FilmSongs)
        autosync_model_to_vectordb(FineArt)
        autosync_model_to_vectordb(FitnessAccessories)
        autosync_model_to_vectordb(Football)
        autosync_model_to_vectordb(FormalShoes)
        autosync_model_to_vectordb(Furniture)
        autosync_model_to_vectordb(GamingAccessories)
        autosync_model_to_vectordb(GamingConsoles)
        autosync_model_to_vectordb(GardenAndOutdoors)
        autosync_model_to_vectordb(GoldAndDiamondJewellery)
        autosync_model_to_vectordb(HandbagsAndClutches)
        autosync_model_to_vectordb(Headphones)
        autosync_model_to_vectordb(HealthAndPersonalCare)
        autosync_model_to_vectordb(HeatingAndCoolingAppliances)
        autosync_model_to_vectordb(HomeAudioAndTheater)
        autosync_model_to_vectordb(HomeDcor)
        autosync_model_to_vectordb(HomeEntertainmentSystems)
        autosync_model_to_vectordb(HomeFurnishing)
        autosync_model_to_vectordb(HomeImprovement)
        autosync_model_to_vectordb(HomeStorage)
        autosync_model_to_vectordb(HouseholdSupplies)
        autosync_model_to_vectordb(IndianClassical)
        autosync_model_to_vectordb(IndianLanguageBooks)
        autosync_model_to_vectordb(IndoorLighting)
        autosync_model_to_vectordb(IndustrialAndScientificSupplies)
        autosync_model_to_vectordb(Innerwear)
        autosync_model_to_vectordb(InternationalMusic)
        autosync_model_to_vectordb(InternationalToyStore)
        autosync_model_to_vectordb(JanitorialAndSanitationSupplies)
        autosync_model_to_vectordb(Jeans)
        autosync_model_to_vectordb(Jewellery)
        autosync_model_to_vectordb(KidsClothing)
        autosync_model_to_vectordb(KidsFashion)
        autosync_model_to_vectordb(KidsShoes)
        autosync_model_to_vectordb(KidsWatches)
        autosync_model_to_vectordb(KindleEbooks)
        autosync_model_to_vectordb(KitchenStorageAndContainers)
        autosync_model_to_vectordb(KitchenAndDining)
        autosync_model_to_vectordb(KitchenAndHomeAppliances)
        autosync_model_to_vectordb(LabAndScientific)
        autosync_model_to_vectordb(LingerieAndNightwear)
        autosync_model_to_vectordb(LuxuryBeauty)
        autosync_model_to_vectordb(MakeUp)
        autosync_model_to_vectordb(MensFashion)
        autosync_model_to_vectordb(MotorbikeAccessoriesAndParts)
        autosync_model_to_vectordb(MusicalInstrumentsAndProfessionalAudio)
        autosync_model_to_vectordb(NursingAndFeeding)
        autosync_model_to_vectordb(PcGames)
        autosync_model_to_vectordb(Pantry)
        autosync_model_to_vectordb(PersonalCareAppliances)
        autosync_model_to_vectordb(Refrigerators)
        autosync_model_to_vectordb(RefurbishedAndOpenBox)
        autosync_model_to_vectordb(Rucksacks)
        autosync_model_to_vectordb(Running)
        autosync_model_to_vectordb(StemToysStore)
        autosync_model_to_vectordb(SchoolBags)
        autosync_model_to_vectordb(SchoolTextbooks)
        autosync_model_to_vectordb(SecurityCameras)
        autosync_model_to_vectordb(SewingAndCraftSupplies)
        autosync_model_to_vectordb(Shirts)
        autosync_model_to_vectordb(Shoes)
        autosync_model_to_vectordb(SnackFoods)
        autosync_model_to_vectordb(Speakers)
        autosync_model_to_vectordb(SportsCollectibles)
        autosync_model_to_vectordb(SportsShoes)
        autosync_model_to_vectordb(Sportswear)
        autosync_model_to_vectordb(StrengthTraining)
        autosync_model_to_vectordb(StrollersAndPrams)
        autosync_model_to_vectordb(SubscribeAndSave)
        autosync_model_to_vectordb(SuitcasesAndTrolleyBags)
        autosync_model_to_vectordb(Sunglasses)
        autosync_model_to_vectordb(TShirtsAndPolos)
        autosync_model_to_vectordb(Televisions)
        autosync_model_to_vectordb(TestMeasureAndInspect)
        autosync_model_to_vectordb(Textbooks)
        autosync_model_to_vectordb(TheDesignerBoutique)
        autosync_model_to_vectordb(ToysGiftingStore)
        autosync_model_to_vectordb(ToysAndGames)
        autosync_model_to_vectordb(TravelAccessories)
        autosync_model_to_vectordb(TravelDuffles)
        autosync_model_to_vectordb(ValueBazaar)
        autosync_model_to_vectordb(VideoGamesDeals)
        autosync_model_to_vectordb(Wallets)
        autosync_model_to_vectordb(WashingMachines)
        autosync_model_to_vectordb(Watches)
        autosync_model_to_vectordb(WesternWear)
        autosync_model_to_vectordb(WomensFashion)
        autosync_model_to_vectordb(Yoga)
